
name: workflow_01
on:
  workflow_dispatch:
     inputs:
      example-cron:
        description: 'Ù‹Workflow 2 which will be triggered'
        required: true
        default: 'example-cron'

      example-cron_github_account:
        description: 'GitHub Account Owner'
        required: true
        default: 'bbrozyna'

      example-cron_repo_github:
        description: 'repo-name'
        required: true
        default: 'bbrozyna' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Test
        run: |
          curl -X POST https://api.github.com/repos/bbrozyna/messing-with-cypress/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACTIONS_KEY }} \
          --data '{"event_type": "Trigger Workflow", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
      - uses: actions/checkout@v3
